# Generated by Django 5.2.7 on 2026-01-19 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('behind_image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('bottom_image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin', models.CharField(choices=[('india', 'Indian'), ('foreign', 'Foreign')], default='india', max_length=10)),
            ],
            options={
                'ordering': ['category_name'],
            },
        ),
    ]
