# Generated by Django 5.2.7 on 2026-01-19 07:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('biography', models.TextField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField()),
                ('short_description', models.TextField()),
            ],
        ),
    ]
