# Generated by Django 5.2.7 on 2026-01-19 07:57

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AuthorApp', '0001_initial'),
        ('CategoryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('title', models.CharField(max_length=50, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('front_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('behind_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('top_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('bottom_image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('total_pages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('ratings', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('publications', models.CharField(blank=True, default='Anwar Publications', max_length=100, null=True)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed'), ('maintenance', 'Under Maintenance'), ('pending', 'Pending for Approval')], default='pending', max_length=20)),
                ('language', models.CharField(choices=[('hindi', 'Hindi'), ('urdu', 'Urdu'), ('english', 'English')], default='hindi', max_length=20)),
                ('binding_types', models.CharField(choices=[('hardcover', 'Hardcover'), ('softcover', 'Softcover / Papercover'), ('stitching', 'Stitching'), ('spiral', 'Spiral')], default='softcover', max_length=20)),
                ('edition', models.CharField(choices=[('limited', 'Limited'), ('bulk', 'Bulk'), ('special', 'Special')], default='bulk', max_length=20)),
                ('description', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books_of_author', to='AuthorApp.author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_of_books', to='CategoryApp.category')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('author', 'title')},
            },
        ),
    ]
